export const BRICK = 'BRICK'
export const MAIN_BRICK = 'MAIN_BRICK'
export const PIPE = 'PIPE'
export const PRIMITIVE = 'PRIMITIVE'
export const SELECTABLE_PIPE = 'SELECTABLE_PIPE'
export const SURFACE = 'SURFACE'
export const TEST_INPUT = 'TEST_INPUT'
export const TEST_OUTPUT = 'TEST_OUTPUT'
